/**
 * Generated by tsnapi — public API snapshot of `immili`
 */
// #region Interfaces
export interface ActionNamespace {
  readonly [key: string]: ActionMethod | ActionNamespace;
}
export interface ActionTree<S extends object, A extends ActionNamespace> {
  readonly [ACTION_TREE]: ActionTreeMeta<S, A>;
}
export interface RootHelpers<S extends object> {
  merge(_: DeepPatch<S>): void;
  draft(_: (_: Draft<S>) => void): void;
}
export interface StateTree<S extends object> {
  readonly [STATE_TREE]: StateTreeMeta<S>;
}
// #endregion

// #region Types
export type BoundActions<S extends object, A extends ActionNamespace> = BoundActionNamespace<A> & RootHelpers<S>;
export type DeepPatch<T> = T extends readonly unknown[] | Function | Promise<any> | Date | RegExp | {
  [immerable]: false;
} ? T : T extends object ? { [K in keyof T]?: DeepPatch<T[K]> } : T;
// #endregion

// #region Functions
export declare function createActions<S extends object, A extends ActionNamespace>(_: StateTree<S>, _: (_: Draft<S>) => A): ActionTree<S, A>;
export declare function createStateTree<S extends object>(_: S): StateTree<S>;
export declare function useActions<S extends object, A extends ActionNamespace>(_: ActionTree<S, A>, _: Immutable<S>): BoundActions<S, A>;
export declare function useStateTree<S extends object>(_: StateTree<S>): Immutable<S>;
// #endregion